---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: {{ include "grafana-cr.fullname" . }}
  labels:
  {{- include "grafana-cr.labels" . | nindent 4 }}
spec:
  deployment:
    skipCreateAdminAccount: True
    envFrom:
      - secretRef:
          name: {{ include "grafana-cr.fullname" . }}-creds
  config:
    analytics:
      check_for_updates: false
      reporting_enabled: false
    auth:
      disable_login_form: true
      disable_signout_menu: true
      sigv4_auth_enabled: true
    auth.basic:
      enabled: false
    auth.proxy:
      auto_sign_up: true
      enabled: true
      header_name: X-Forwarded-User
    log:
      level: {{ .Values.logLevel }}
      mode: console
    security:
      admin_user: system:does-not-exist
      cookie_secure: true
    users:
      auto_assign_org: true
      auto_assign_org_role: {{ .Values.oauthProxy.orgRoleAssigned }}
      default_theme: light
      editors_can_admin: true
      viewers_can_edit: true
  containers:
    - image: 'quay.io/openshift/origin-oauth-proxy:4.12'
      name: grafana-proxy
      args:
      - -provider=openshift
      - -https-address=:9091
      - -http-address=
      - -email-domain=*
      - -upstream=http://localhost:3000
      - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
      - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
      - -tls-cert=/etc/tls/private/tls.crt
      - -tls-key=/etc/tls/private/tls.key
      - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
      - -openshift-service-account=grafana-serviceaccount
      - -openshift-ca=/etc/pki/tls/cert.pem
      - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      - -cookie-secret-file=/etc/proxy/secrets/session_secret
      - -cookie-expire=24h
      - -scope=user:info user:check-access user:list-projects
      - -pass-access-token=true
      - -pass-basic-auth=false
      - -display-htpasswd-form=false
      - -htpasswd-file=/etc/proxy/htpasswd/auth
      - -skip-provider-button=true
      ports:
        - containerPort: 9091
          name: grafana-proxy
      resources: {}
      volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-{{ include "grafana-cr.fullname" . }}-tls
          readOnly: false
        - mountPath: /etc/proxy/secrets
          name: secret-{{ include "grafana-cr.fullname" . }}-proxy
          readOnly: false
        - mountPath: /etc/proxy/htpasswd
          name: secret-{{ include "grafana-cr.fullname" . }}-htpasswd
          readOnly: true
  secrets:
    - {{ include "grafana-cr.fullname" . }}-tls
    - {{ include "grafana-cr.fullname" . }}-proxy
    - {{ include "grafana-cr.fullname" . }}-htpasswd
  service:
    ports:
      - name: grafana-proxy
        port: 9091
        protocol: TCP
        targetPort: grafana-proxy
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: {{ include "grafana-cr.fullname" . }}-tls
  ingress:
    enabled: True
    targetPort: grafana-proxy
    termination: reencrypt
  serviceAccount:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}'
      {{- with .Values.serviceAccountAnnotations }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  dashboardLabelSelector:
    - matchExpressions:
        - { key: "app", operator: In, values: ['grafana'] }
