apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  pipelines:
  - name: logs-to-default
    inputRefs:
    {{ if .Values.forward_infrastructure }}
    - infrastructure
    {{ end }}
    {{ if .Values.forward_application }}
    - application
    {{ end }}
    {{ if .Values.forward_audit }}
    - audit
    {{ end }}
    outputRefs:
    - default
