apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rosa-loki.fullname" . }}-loki-creds
  namespace: openshift-logging
  labels:
    {{- include "rosa-loki.labels" . | nindent 4 }}
stringData:
  access_key_id: {{ .Values.aws_access_key_id }}
  access_key_secret: {{ .Values.aws_access_key_secret }}
  bucketnames: {{ .Values.aws_s3_bucket_name }}
  endpoint: https://s3.{{ .Values.aws_region }}.amazonaws.com
  region: {{ .Values.aws_region }}
