apiVersion: v2
appVersion: 0.1.0
description: Register an OpenShift or Kubernetes cluster with ACM
name: acm-registration
type: application
version: 0.2.2
home: "https://rh-mobb.github.io/helm-charts/"
maintainers:
  - name: rh-mobb
