---
{{ if eq .Values.clusterMetrics.method "grafana-agent" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
  labels:
    {{- include "aro-thanos-af.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
  labels:
    {{- include "aro-thanos-af.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
  labels:
    {{- include "aro-thanos-af.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
subjects:
- kind: ServiceAccount
  name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
  labels:
    {{- include "aro-thanos-af.labels" . | nindent 4 }}
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/grafana/agent-cm.yaml") . | sha256sum }}
      labels:
        name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
    spec:
      containers:
      - args:
        - -config.file=/etc/agent/agent.yaml
        command:
        - /bin/agent
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: grafana/agent:v0.28.0
        imagePullPolicy: IfNotPresent
        name: agent
        ports:
        - containerPort: 12345
          name: http-metrics
        volumeMounts:
        - mountPath: /etc/agent
          name: grafana-agent
      serviceAccount: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
      volumes:
      - configMap:
          name: {{ include "aro-thanos-af.fullname" . }}-grafana-agent
        name: grafana-agent
---
{{ end }}
